INSERT INTO USERS (USERNAME, PASSWORD) VALUES ('iamscratches', '$2a$11$/o4KpRkQ3UxQYEfn2QiHUOZgSQUCx21nrtn/GsEPoQTwSViqu2krq');
INSERT INTO USERS (USERNAME, PASSWORD) VALUES ('subhankb', '$2a$11$9tsvMMw4BJ2NclcT4S8eXu/ut1KCGXwtiqmKaBQE/eNPQOVH8EltS');

INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('iamscratches', 'USER');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('iamscratches', 'ADMIN');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('subhankb', 'USER');